### ISSUE TITLE
Modification titre : Gras et souligné 

### ISSUE THREAD

**Issue by GitHub-Sebastien** [FerrandezBenjamin/CV#3]
Je vais modifié le css pour modifier le titre 
`hobby et autres`
 pour qu'il apparaisse en gras, souligné et augmenter la taille du texte dans le index.html

**Comment by FerrandezBenjamin** [comment]
ok !

**Comment by GitHub-Sebastien** [comment]
#4

**Comment by GitHub-Sebastien** [comment]
e90e706da7c5f6a7c7a2bbff1dfee839a752d881

**Comment by GitHub-Sebastien** [comment]
Changement effectuer @julienma 
eca2af908f67deb4be90081ef75b46bceba4e333 
c3277c7cfbeb9c22f12fb20f6f74cac2379690b9

**Comment by julienma** [comment]
Ok pour moi @GitHub-Sebastien
